-- This is an empty migration.
INSERT INTO "permissions" (
    "name",
    "action",
    "subject",
    "type"
) VALUES
('category:read', 'read', 'Category', 'can'),
('category:create', 'create', 'Category', 'can'),
('category:update', 'update', 'Category', 'can'),
('category:delete', 'delete', 'Category', 'can'),
('category:manage', 'manage', 'Category', 'can'),
('tag:read', 'read', 'Tag', 'can'),
('tag:create', 'create', 'Tag', 'can'),
('tag:update', 'update', 'Tag', 'can'),
('tag:delete', 'delete', 'Tag', 'can'),
('tag:manage', 'manage', 'Tag', 'can'),
('post:read', 'read', 'Post', 'can'),
('post:create', 'create', 'Post', 'can'),
('post:update', 'update', 'Post', 'can'),
('post:delete', 'delete', 'Post', 'can'),
('post:manage', 'manage', 'Post', 'can'),
('comment:read', 'read', 'Comment', 'can'),
('comment:create', 'create', 'Comment', 'can'),
('comment:update', 'update', 'Comment', 'can'),
('comment:delete', 'delete', 'Comment', 'can'),
('comment:manage', 'manage', 'Comment', 'can'),
('postReaction:read', 'read', 'PostReaction', 'can'),
('postReaction:create', 'create', 'PostReaction', 'can'),
('postReaction:update', 'update', 'PostReaction', 'can'),
('postReaction:delete', 'delete', 'PostReaction', 'can'),
('postReaction:manage', 'manage', 'PostReaction', 'can'),
('commentReaction:read', 'read', 'CommentReaction', 'can'),
('commentReaction:create', 'create', 'CommentReaction', 'can'),
('commentReaction:update', 'update', 'CommentReaction', 'can'),
('commentReaction:delete', 'delete', 'CommentReaction', 'can'),
('commentReaction:manage', 'manage', 'CommentReaction', 'can'),
('bookmark:read', 'read', 'Bookmark', 'can'),
('bookmark:create', 'create', 'Bookmark', 'can'),
('bookmark:update', 'update', 'Bookmark', 'can'),
('bookmark:delete', 'delete', 'Bookmark', 'can'),
('bookmark:manage', 'manage', 'Bookmark', 'can'),
('followAuthor:read', 'read', 'FollowAuthor', 'can'),
('followAuthor:create', 'create', 'FollowAuthor', 'can'),
('followAuthor:update', 'update', 'FollowAuthor', 'can'),
('followAuthor:delete', 'delete', 'FollowAuthor', 'can'),
('followAuthor:manage', 'manage', 'FollowAuthor', 'can')